# Welcome to Codeaft
title: Codeaft
url: https://codeaft.github.io
email: codeaft@outlook.com
tagline: Let's learn and celebrate success together
founder: Shubham Darda

# Resources
codeaft_css: assets/css/codeaft.css
codeaft_js: assets/js/codeaft.js
bs_css: https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css
bs_cssi: sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT
bs_js: https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js
bs_jsi: sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO
bs_icons: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.css
jquery: https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
og: https://raw.githubusercontent.com/codeaft/codeaft.github.io/master/assets/images/logo.png
logo: assets/images/logo.png
advertise: assets/images/advertise.png

# Filename
highlighter: rouge
cfile: "<span class='bi bi-file-code'> codeaft.c</span>"
cppfile: "<span class='bi bi-file-code'> codeaft.cpp</span>"
javafile: "<span class='bi bi-filetype-java'> Codeaft.java</span>"
pyfile: "<span class='bi bi-filetype-py'> codeaft.py</span>"
rfile: "<span class='bi bi-file-code'> codeaft.r</span>"
juliafile: "<span class='bi bi-file-code'> codeaft.jl</span>"
csfile: "<span class='bi bi-filetype-cs'> Program.cs</span>"
fsfile: "<span class='bi bi-file-code'> Program.fs</span>"
rustfile: "<span class='bi bi-file-code'> codeaft.rs</span>"
lispfile: "<span class='bi bi-file-code'> codeaft.lisp</span>"
shfile: "<span class='bi bi-filetype-sh'> codeaft.sh</span>"
asmfile: "<span class='bi bi-file-code'> codeaft.asm</span>"
vbsfile: "<span class='bi bi-file-code'> codeaft.vbs</span>"
csvfile: "<span class='bi bi-filetype-csv'> codeaft.csv</span>"
jsonfile: "<span class='bi bi-filetype-json'> codeaft.json</span>"
excelfile: "<span class='bi bi-filetype-xlsx'> codeaft.xlsx</span>"

# Execution
runc: "codeaft@codeaft:~$ <mark>gcc codeaft.c</mark><br>codeaft@codeaft:~$ <mark>./a.out</mark>"
runcpp: "codeaft@codeaft:~$ <mark>g++ codeaft.cpp</mark><br>codeaft@codeaft:~$ <mark>./a.out</mark>"
runjava: "codeaft@codeaft:~$ <mark>javac Codeaft.java</mark><br>codeaft@codeaft:~$ <mark>java KW</mark>"
runpy: "codeaft@codeaft:~$ <mark>python3 codeaft.py</mark>"
runjulia: "codeaft@codeaft:~$ <mark>julia codeaft.jl</mark>"
runcs: "codeaft@codeaft:~/csharp$ <mark>dotnet run</mark>"
runfs: "codeaft@codeaft:~/fsharp$ <mark>dotnet run</mark>"
runrust: "codeaft@codeaft:~$ <mark>rustc codeaft.rs</mark><br>codeaft@codeaft:~$ <mark>./codeaft</mark>"
runlisp: "codeaft@codeaft:~$ <mark>clisp codeaft.lisp</mark>"
runsh: "codeaft@codeaft:~$ <mark>bash codeaft.sh</mark>"
runcg: "codeaft@codeaft:~$ <mark>g++ codeaft.cpp -lgraph</mark><br>codeaft@codeaft:~$ <mark>./a.out</mark>"
runopengl: "codeaft@codeaft:~$ <mark>g++ codeaft.cpp -lGL -lGLU -lglut</mark><br>codeaft@codeaft:~$ <mark>./a.out</mark>"
runasm: "codeaft@codeaft:~$ <mark>nasm -felf64 codeaft.asm</mark><br>codeaft@codeaft:~$ <mark>ld codeaft.o && ./a.out</mark>"
output: "<span class='bi bi-terminal'> Output</span>"

defaults:
  -
   scope:
      path: "assets/css/codeaft.css"
   values:
      layout: none
  -
   scope:
      path: "404"
   values:
      layout: none
  -
   scope:
      path: ""
   values:
      layout: "modern"

plugins:
   - jekyll-sitemap

include: ['pages']

# Exclude from processing
exclude:
   - _site
   - .bundle
   - .jekyll-cache
   - automated_tests
   - vendor
   - .gitignore
   - .jekyll-metadata
   - CODE_OF_CONDUCT.md
   - Gemfile
   - Gemfile.lock
   - LICENSE
   - README.md
   - setup.py